stages:
  - build
  - tag

include:
  - project: 'cms-analysis/general/container-image-ci-templates'
    file:
      - 'kaniko-image.gitlab-ci.yml'
      - 'skopeo.gitlab-ci.yml'

variables:
    CONTEXT_DIR: ""
    DOCKER_FILE_NAME: "Dockerfile"
    GIT_SUBMODULE_STRATEGY: recursive
    PUSH_IMAGE: "true"
    ACCELERATED_IMAGE: "true"
    BUILD_ARGS: ""
    SCAN_IMAGE: "false"

.build_docker_template:
  extends: .build_kaniko
  only:
    refs:
      - pushes
      - merge_requests
    changes:
      - Dockerfile
      - requirements.txt 

#--------------------------------------------------------------------
# Build images and tag with short commit SHA
build_docker:
  extends: .build_docker_template
  variables:
    BUILD_ARGS: "FROM_IMAGE='/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmsml/cmsml:3.11'"
    REGISTRY_IMAGE_PATH: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    # TO_COMMIT: ${CI_REGISTRY_IMAGE}:lxplus-cc7-latest

#--------------------------------------------------------------------
# Tag images on default branch as latest

build_docker_latest:
  extends: .tag_skopeo
  variables:
    IMAGE_ORIGIN_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    IMAGE_DESTINATION_TAG: ${CI_REGISTRY_IMAGE}:latest
  rules:
    - changes:
      - Dockerfile
      - requirements.txt

#-------------------------------------------------------------------
# Tag images using git tag
build_docker_tagged:
  extends: .tag_skopeo
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    IMAGE_ORIGIN_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    IMAGE_DESTINATION_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    
