# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev51+g38a6aa4.d20230407'
__version_tuple__ = version_tuple = (0, 1, 'dev51', 'g38a6aa4.d20230407')
